// Generated by scripts/import-gan-huaiyue.py; reviewed source rows in docs/gan-huaiyue-provenance.json.
import type { AtlasLocality } from "./types";
/** Reuses the existing, explicitly geographic huaiyue-localities cluster. */
export const atlasGanHuaiyueLocalities: AtlasLocality[] = [
  {
    "id": "gan-qianshan-meicheng",
    "name": "Meicheng",
    "nativeName": "梅城",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.579722222,
      30.634444444
    ],
    "scope": "潜山梅城 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=270",
      "locator": "Named settlement 潜山梅城; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340882, row 4. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "梅城镇",
      "潜山梅城"
    ],
    "geographySource": {
      "title": "Wikidata · 梅城镇",
      "url": "https://www.wikidata.org/entity/Q11114593",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-susong-jiugu",
    "name": "Jiugu",
    "nativeName": "九姑",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.23205,
      30.10949
    ],
    "scope": "宿松九姑 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=270",
      "locator": "Named settlement 宿松九姑; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340826, row 5. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "九姑乡",
      "宿松九姑"
    ],
    "geographySource": {
      "title": "Wikidata · 九姑乡",
      "url": "https://www.wikidata.org/entity/Q10878769",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-wangjiang-yatan",
    "name": "Yatan",
    "nativeName": "鸦滩",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.55358,
      30.31834
    ],
    "scope": "望江鸦滩 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=270",
      "locator": "Named settlement 望江鸦滩; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340827, row 8. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "鸦滩镇",
      "望江鸦滩"
    ],
    "geographySource": {
      "title": "Wikidata · 鸦滩镇",
      "url": "https://www.wikidata.org/entity/Q11174400",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-taihu-xincang",
    "name": "Xincang",
    "nativeName": "新仓",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.42236,
      30.4313
    ],
    "scope": "太湖新仓 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=270",
      "locator": "Named settlement 太湖新仓; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340825, row 6. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "新仓镇",
      "太湖新仓"
    ],
    "geographySource": {
      "title": "Wikidata · 新仓镇",
      "url": "https://www.wikidata.org/entity/Q11081067",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-dongzhi-yaodu",
    "name": "Yaodu",
    "nativeName": "尧渡",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      117.01654,
      30.09584
    ],
    "scope": "东至尧渡 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. Dongzhi County contains Gan, Mandarin and Hui references; Xu explicitly places Yaodu in the Gan comparison. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=270",
      "locator": "Named settlement 东至尧渡; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 341721, row 25. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "尧渡镇",
      "东至尧渡"
    ],
    "geographySource": {
      "title": "Wikidata · 尧渡镇",
      "url": "https://www.wikidata.org/entity/Q11040032",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-yuexi-tiantang",
    "name": "Tiantang",
    "nativeName": "天堂",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.35482,
      30.84829
    ],
    "scope": "岳西天堂 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=272",
      "locator": "Named settlement 岳西天堂; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340828, row 11. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "天堂镇",
      "岳西天堂"
    ],
    "geographySource": {
      "title": "Wikidata · 天堂镇",
      "url": "https://www.wikidata.org/entity/Q10939297",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-susong-erlang",
    "name": "Erlang",
    "nativeName": "二郎",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.05548,
      30.2785
    ],
    "scope": "宿松二郎 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The Erlang readings are reproduced from Sun Yizhi 2002. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=274",
      "locator": "Named settlement 宿松二郎; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340826, row 5. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "二郎镇",
      "宿松二郎"
    ],
    "geographySource": {
      "title": "Wikidata · 二郎镇",
      "url": "https://www.wikidata.org/entity/Q10880479",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-huaining-shipai",
    "name": "Shipai",
    "nativeName": "石牌",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.64402,
      30.41186
    ],
    "scope": "怀宁石牌 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=274",
      "locator": "Named settlement 怀宁石牌; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340822, row 3. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "石牌镇",
      "怀宁石牌"
    ],
    "geographySource": {
      "title": "Wikidata · 石牌镇",
      "url": "https://www.wikidata.org/entity/Q14343148",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  },
  {
    "id": "gan-wangjiang-saikou",
    "name": "Saikou",
    "nativeName": "赛口",
    "groupId": "gan",
    "branchId": "huaiyue",
    "clusterId": "huaiyue-localities",
    "coordinates": [
      116.8149,
      30.40308
    ],
    "scope": "望江赛口 is the named settlement reference in Xu Jian’s 2022 comparison. These are character readings, not a uniform accent across the surrounding county. Collection date and speaker details are unspecified. The map uses a separate approximate town anchor; local place-name IPA is not yet collected.",
    "source": {
      "title": "Xu Jian 徐建 2022 · 皖西南方言开口一二等韵读齐齿呼现象考察",
      "url": "https://geolinguistics.sakura.ne.jp/Monograph/SiG-mono2-2-xia-ebook.pdf#page=274",
      "locator": "Named settlement 望江赛口; printed pp262–268, tables2–5. Gan membership: Xu2022. Huai–Yue county alignment: Jing2025, county 340827, row 8. Geographic collection, not a new linguistic subdivision."
    },
    "aliases": [
      "赛口镇",
      "望江赛口"
    ],
    "geographySource": {
      "title": "Wikidata · 赛口镇",
      "url": "https://www.wikidata.org/entity/Q14345798",
      "locator": "Exact Chinese settlement label and P131 county match; P625 approximate town anchor, retrieved 2026-10-09, CC0. Not a recording address or language boundary."
    }
  }
];
