import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import RomanizationPage from "./RomanizationPage";
import {
  romanizationGroups,
  romanizationReadings,
} from "../data/romanization-examples";
import { convertIpa } from "../data/romanization-method";

describe("shared romanization workshop", () => {
  it("gives every group four sourced examples generated by the same converter", () => {
    expect(romanizationGroups.map((g) => g.id)).toEqual([
      "mandarin",
      "min",
      "yue",
      "hakka",
      "wu",
    ]);
    for (const group of romanizationGroups) {
      expect(group.examples).toHaveLength(4);
      for (const word of group.examples) {
        expect(word.groupId).toBe(group.id);
        expect(word.source.url).toMatch(/^https?:/);
        expect(
          convertIpa(word.ipa)
            .map((s) => s.spelling)
            .join(" "),
        ).toBe(word.spelling);
      }
      expect(group.mapped + group.unresolved.length).toBe(
        group.readings.length,
      );
    }
  });
  it("preserves scope and refuses to fill missing sounds or tones", () => {
    expect(romanizationReadings.some((w) => w.localityId === "haifeng")).toBe(
      false,
    );
    expect(romanizationGroups[0].examples[0].registerLabel).toBe(
      "Standard Mandarin · Beijing speaker",
    );
    for (const word of romanizationGroups.flatMap((g) => g.unresolved))
      expect(() => convertIpa(word.ipa), word.id).toThrow();
  });
  it("renders five equal sections, grouped choices, and coverage without Amoy-only links", () => {
    const html = renderToStaticMarkup(
      <MemoryRouter>
        <RomanizationPage />
      </MemoryRouter>,
    );
    for (const group of romanizationGroups) {
      expect(html).toContain(`id="roman-group-${group.id}"`);
      expect(html).toContain(`<optgroup label="${group.name}">`);
    }
    expect(html).toContain("Standard Mandarin · Beijing speaker");
    expect(html).toContain("Current converter coverage");
    expect(html).toContain("not a shared seven-tone inventory");
  });
});
