import { languages } from "../data/languages";
import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import RomanizationPage from "./RomanizationPage";
import {
  romanizationGroups,
  romanizationReadings,
} from "../data/romanization-examples";
import { convertIpa } from "../data/romanization-method";
import { learningPlaces } from "../data/learning/places";
import { getLocalLearning } from "../data/learning";

describe("shared romanization workshop", () => {
  it("offers every published IPA reading with its original tone convention", () => {
    const allWords = learningPlaces.flatMap((point) => getLocalLearning(point).words);
    expect(romanizationReadings).toHaveLength(allWords.length);
    for (const word of romanizationReadings) {
      if (!word.spelling) {
        expect(word.id).toMatch(/^tunxi-hui:lu2017-tunxi-(first|second|third)-strong$/);
        expect(word.registerLabel).toContain('tone on -le not supplied');
        expect(() => convertIpa(word.ipa, word.toneNotation)).toThrow(/pitch contour/);
        continue;
      }
      expect(convertIpa(word.ipa, word.toneNotation ?? "unspecified")
        .map((syllable) => syllable.spelling).join(" "), word.id).toBe(word.spelling);
      expect(word.spelling, word.id).toBeTruthy();
    }
    expect(romanizationReadings.filter(word => !word.spelling)).toHaveLength(3);
  });
  it("gives every group four sourced examples generated by the same converter", () => {
    expect(romanizationGroups.map((g) => g.id)).toEqual(languages.map(group => group.id));
    for (const group of romanizationGroups) {
      expect(group.examples).toHaveLength(Math.min(4, group.mapped));
      for (const word of group.examples) {
        expect(word.groupId).toBe(group.id);
        expect(word.source.url).toMatch(/^https?:/);
        expect(
          convertIpa(word.ipa, word.toneNotation ?? "unspecified")
            .map((s) => s.spelling)
            .join(" "),
        ).toBe(word.spelling);
      }
      expect(group.mapped + group.unresolved.length).toBe(
        group.readings.length,
      );
    }
  });
  it("includes segment-only sources without inventing tones", () => {
    const readings = romanizationReadings.filter((word) => word.localityId === "haifeng");
    expect(readings.length).toBeGreaterThan(0);
    for (const word of readings) {
      expect(word.toneNotation).toBe("unspecified");
      const converted = convertIpa(word.ipa, "unspecified");
      expect(converted.every((syllable) => syllable.tone === "")).toBe(true);
      expect(converted.map((syllable) => syllable.spelling).join(" ")).toBe(word.spelling);
      expect(() => convertIpa(word.ipa)).toThrow(/pitch contour/);
    }
    expect(romanizationGroups[0].examples[0].registerLabel).toBe(
      "Standard Mandarin · Beijing speaker",
    );
    for (const word of romanizationGroups.flatMap((g) => g.unresolved))
      expect(() => convertIpa(word.ipa, word.toneNotation ?? "unspecified"), word.id).toThrow();
  });
  it("renders all published sections, grouped choices, and coverage without Amoy-only links", () => {
    const html = renderToStaticMarkup(
      <MemoryRouter>
        <RomanizationPage />
      </MemoryRouter>,
    );
    for (const group of romanizationGroups) {
      expect(html).toContain(`id="roman-group-${group.id}"`);
      expect(html).toContain(`<optgroup label="${group.name}">`);
    }
    expect(html).toContain("Standard Mandarin · Beijing speaker");
    expect(html).toContain("Current converter coverage");
    expect(html).toContain("not a shared seven-tone inventory");
    expect(html).toContain("Tones not supplied");
    expect(html).toContain("Source tone categories");
    expect(html).toContain("ă represents [ɐ]; a~ represents nasal [ã]");
    expect(html).toContain("The same IPA gets the same spelling everywhere");
    expect(html).toContain("[y] → ü, [ju] → yu, and [jy] → yü");
    expect(html).not.toContain("One sound, one working spelling");
  });
});


describe("readability-first workshop", () => {
  it("shows a sourced same-spelling pair without hiding the Suzhou vowel contrast", () => {
    const html = renderToStaticMarkup(<MemoryRouter><RomanizationPage /></MemoryRouter>);
    const section = html.split('aria-labelledby="roman-shared-example"')[1]?.split("</div>")[0];
    expect(section).toBeTruthy();
    expect(section).toContain("Same spelling, different sounds");
    const words = ["衣", "煙"].map((han) => romanizationReadings.find((word) =>
      word.localityId === "suzhou" && word.han === han,
    )!);
    expect(words.map((word) => word.ipa)).toEqual(["[i44]", "[ɪ44]"]);
    expect(words.map((word) => word.spelling)).toEqual(["i44", "i44"]);
    for (const word of words) {
      expect(section).toContain(word.han);
      expect(section).toContain(word.displayIpa);
      expect(section).toContain(word.source.url.replaceAll("&", "&amp;"));
    }
    expect(section!.match(/<strong>i44<\/strong>/g)).toHaveLength(2);
  });
  it("starts from sourced 灰 and presents nasal and central-vowel contrasts", () => {
    const html = renderToStaticMarkup(<MemoryRouter><RomanizationPage /></MemoryRouter>);
    const ash = romanizationReadings.find((word) => word.id.endsWith(":beijing-city-ipa-ash"));
    expect(ash).toBeDefined();
    expect(html).toContain(`<textarea`);
    expect(html).toMatch(/<textarea[^>]*>xuei˥<\/textarea>/);
    expect(html).toContain('<output for="roman-ipa">huei5</output>');
    for (const [locality, han, spelling] of [
      ["beijing-city", "說", "shuo55"],
      ["zhangzhou", "飯", "pui~22"],
      ["guangzhou", "心", "săm55"],
    ]) {
      const word = romanizationReadings.find((entry) => entry.localityId === locality && entry.han === han);
      expect(word?.spelling).toBe(spelling);
      expect(html).toContain(`<strong>${spelling}</strong>`);
      expect(html).toContain(word!.source.url.replaceAll("&", "&amp;"));
    }
    expect(html).toContain("Standard Mandarin · Beijing speaker");
    expect(html).toContain("sh, not sr");
    expect(html).toContain("za~·T3 he·T2");
    expect(html).toContain("sam55");
    expect(html).toContain("săm55");
    expect(html).toContain("a~");
    expect(html).toContain("a:");
    expect(html).toContain("Syllabicity and unreleased");
    expect(html).not.toContain("Trial sh, š");
  });
});
