import { describe, expect, it } from "vitest";
import { renderToStaticMarkup } from "react-dom/server";
import { MemoryRouter } from "react-router-dom";
import RomanizationPage from "./RomanizationPage";
import {
  romanizationGroups,
  romanizationReadings,
} from "../data/romanization-examples";
import { convertIpa } from "../data/romanization-method";
import { mapPoints } from "../data/languages";
import { getLocalLearning } from "../data/learning";

describe("shared romanization workshop", () => {
  it("offers every published IPA reading with its original tone convention", () => {
    const allWords = mapPoints.flatMap((point) => getLocalLearning(point).words);
    expect(romanizationReadings).toHaveLength(allWords.length);
    for (const word of romanizationReadings) {
      expect(convertIpa(word.ipa, word.toneNotation ?? "unspecified")
        .map((syllable) => syllable.spelling).join(" "), word.id).toBe(word.spelling);
      expect(word.spelling, word.id).toBeTruthy();
    }
  });
  it("gives every group four sourced examples generated by the same converter", () => {
    expect(romanizationGroups.map((g) => g.id)).toEqual([
      "mandarin",
      "min",
      "yue",
      "hakka",
      "wu",
    ]);
    for (const group of romanizationGroups) {
      expect(group.examples).toHaveLength(4);
      for (const word of group.examples) {
        expect(word.groupId).toBe(group.id);
        expect(word.source.url).toMatch(/^https?:/);
        expect(
          convertIpa(word.ipa, word.toneNotation ?? "unspecified")
            .map((s) => s.spelling)
            .join(" "),
        ).toBe(word.spelling);
      }
      expect(group.mapped + group.unresolved.length).toBe(
        group.readings.length,
      );
    }
  });
  it("includes segment-only sources without inventing tones", () => {
    const readings = romanizationReadings.filter((word) => word.localityId === "haifeng");
    expect(readings.length).toBeGreaterThan(0);
    for (const word of readings) {
      expect(word.toneNotation).toBe("unspecified");
      const converted = convertIpa(word.ipa, "unspecified");
      expect(converted.every((syllable) => syllable.tone === "")).toBe(true);
      expect(converted.map((syllable) => syllable.spelling).join(" ")).toBe(word.spelling);
      expect(() => convertIpa(word.ipa)).toThrow(/pitch contour/);
    }
    expect(romanizationGroups[0].examples[0].registerLabel).toBe(
      "Standard Mandarin · Beijing speaker",
    );
    for (const word of romanizationGroups.flatMap((g) => g.unresolved))
      expect(() => convertIpa(word.ipa, word.toneNotation ?? "unspecified"), word.id).toThrow();
  });
  it("renders five equal sections, grouped choices, and coverage without Amoy-only links", () => {
    const html = renderToStaticMarkup(
      <MemoryRouter>
        <RomanizationPage />
      </MemoryRouter>,
    );
    for (const group of romanizationGroups) {
      expect(html).toContain(`id="roman-group-${group.id}"`);
      expect(html).toContain(`<optgroup label="${group.name}">`);
    }
    expect(html).toContain("Standard Mandarin · Beijing speaker");
    expect(html).toContain("Current converter coverage");
    expect(html).toContain("not a shared seven-tone inventory");
    expect(html).toContain("Tones not supplied");
    expect(html).toContain("Source tone categories");
    expect(html).toContain("Trial ă represents [ɐ]; ã represents nasal [ã]");
  });
});
