// Bounded character-reading selection; generated by scripts/import-hui-wuyuan.py.
import type { BranchLearning } from "./types";
export const huiWuyuanLearning: BranchLearning[] = [
  {
    "branchId": "hui/qiwu",
    "words": [
      {
        "id": "hu2016-youshan-t6-c1",
        "han": "脳",
        "english": "Character 脳",
        "ipa": "[la31]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 脳・老. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 1",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c2",
        "han": "老",
        "english": "Character 老",
        "ipa": "[la31]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 脳・老. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 2",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c3",
        "han": "男",
        "english": "Character 男",
        "ipa": "[num21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 男・欄. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 3",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c4",
        "han": "欄",
        "english": "Character 欄",
        "ipa": "[num21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 男・欄. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 4",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c5",
        "han": "女",
        "english": "Character 女",
        "ipa": "[ny31]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 5",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c6",
        "han": "呂",
        "english": "Character 呂",
        "ipa": "[li31]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 6",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c7",
        "han": "農",
        "english": "Character 農",
        "ipa": "[nɑm21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 農・龍. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 7",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c8",
        "han": "龍",
        "english": "Character 龍",
        "ipa": "[nɑm21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. The source’s merged cell explicitly covers 農・龍. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 8",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t6-c9",
        "han": "六",
        "english": "Character 六",
        "ipa": "[læ51]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.74, table 6, 游山 row, column 9",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "id": "hu2016-youshan-t7-c1",
        "han": "修",
        "english": "Character 修",
        "ipa": "[sæ33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.75, table 7, 游山 row, column 1",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=10"
        }
      },
      {
        "id": "hu2016-youshan-t7-c2",
        "han": "休",
        "english": "Character 休",
        "ipa": "[ɕiæ33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.75, table 7, 游山 row, column 2",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=10"
        }
      },
      {
        "id": "hu2016-youshan-t7-c3",
        "han": "焦",
        "english": "Character 焦",
        "ipa": "[tsiaɔ33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.75, table 7, 游山 row, column 3",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=10"
        }
      },
      {
        "id": "hu2016-youshan-t7-c4",
        "han": "驕",
        "english": "Character 驕",
        "ipa": "[tɕio33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.75, table 7, 游山 row, column 4",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=10"
        }
      },
      {
        "id": "hu2016-youshan-t12-c3",
        "han": "毛",
        "english": "Character 毛",
        "ipa": "[ma21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 3",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      },
      {
        "id": "hu2016-youshan-t12-c4",
        "han": "茅",
        "english": "Character 茅",
        "ipa": "[maɔ21]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 4",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      },
      {
        "id": "hu2016-youshan-t12-c5",
        "han": "高",
        "english": "Character 高",
        "ipa": "[ka33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 5",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      },
      {
        "id": "hu2016-youshan-t12-c6",
        "han": "交",
        "english": "Character 交",
        "ipa": "[kaɔ33]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 6",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      },
      {
        "id": "hu2016-youshan-t12-c7",
        "han": "好",
        "english": "Character 好",
        "ipa": "[xa35]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Source heading specifies verb 好. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 7",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      },
      {
        "id": "hu2016-youshan-t12-c8",
        "han": "孝",
        "english": "Character 孝",
        "ipa": "[xaɔ35]",
        "toneNotation": "pitch-contour",
        "localityId": "youshan-hui",
        "learningKind": "character-reading",
        "reading": "Survey character reading",
        "registerLabel": "Youshan village · 2015 survey · one older speaker · character reading",
        "note": "Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.",
        "source": {
          "title": "Hu Guiyue 2016 · p.80, table 12, 游山 row, column 8",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      }
    ],
    "soundNotes": [
      {
        "title": "女 and 呂",
        "text": "In the 2015 Youshan sample, 女 [ny31] and 呂 [li31] differ in both initial and vowel. Both carry the source’s 31 pitch contour. 男 and 欄 share [num21], while 農 and 龍 share [nɑm21].",
        "localityIds": [
          "youshan-hui"
        ],
        "source": {
          "title": "Hu 2016 · p.74, table 6, Youshan row",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=9"
        }
      },
      {
        "title": "A vowel followed by [ɔ]",
        "text": "The Youshan sample contrasts 毛 [ma21] with 茅 [maɔ21], and 高 [ka33] with 交 [kaɔ33]. Each pair keeps the same pitch contour while the second reading adds [ɔ]. These are the source’s character readings from one 2015 speaker.",
        "localityIds": [
          "youshan-hui"
        ],
        "source": {
          "title": "Hu 2016 · p.80, table 12, Youshan row",
          "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=15"
        }
      }
    ],
    "culture": [
      {
        "title": "Houses beside the Junyuan River",
        "text": "The Junyuan River crosses Youshan between rows of Hui-style houses. Zhao Huafu’s village field study describes five stone bridges connecting the riverbanks; the town government’s 2023 account also records repairs to the river channel and stone-paved lanes.",
        "localityIds": [
          "youshan-hui"
        ],
        "source": {
          "title": "Zhao Huafu · Youshan Dong-lineage field study, opening description",
          "url": "https://www.sinoss.net/uploadfile/2010/1130/614.pdf#page=1"
        }
      },
      {
        "title": "Jiahui Hall",
        "text": "Zhao Huafu’s field study describes Jiahui Hall in the centre of Youshan: a gate hall, a courtyard and spaces for ceremonies and ancestral tablets. Its account distinguishes the village’s common ancestral hall from the smaller halls of individual lineage branches.",
        "localityIds": [
          "youshan-hui"
        ],
        "source": {
          "title": "Zhao Huafu · Youshan Dong-lineage field study, section 1",
          "url": "https://www.sinoss.net/uploadfile/2010/1130/614.pdf#page=2"
        }
      }
    ],
    "resources": [
      {
        "title": "Youshan’s 2015 pronunciation sample",
        "description": "Hu’s study identifies the village and speaker-selection method on pp.68–69. The selected character readings come from tables 6, 7 and 12.",
        "localityIds": [
          "youshan-hui"
        ],
        "kind": "Study",
        "url": "https://kanazawa-u.repo.nii.ac.jp/record/5581/files/AA12162559-32-67-83.pdf#page=3"
      },
      {
        "title": "A field study of Youshan village",
        "description": "Zhao Huafu’s village investigation covers ancestral halls, bridges, commerce and local customs, with historical sources distinguished from field observations.",
        "localityIds": [
          "youshan-hui"
        ],
        "kind": "Culture",
        "url": "https://www.sinoss.net/uploadfile/2010/1130/614.pdf"
      },
      {
        "title": "Youshan heritage conservation",
        "description": "Zhentou Town government’s August 2023 reply identifies Youshan village and documents its historic buildings, lane repairs and conservation plans. Read the official reply below the resident’s request.",
        "localityIds": [
          "youshan-hui"
        ],
        "kind": "Culture",
        "url": "https://wenz.jxnews.com.cn/ms/viewpage/202308/view_340107.html"
      }
    ]
  }
];
