// Bounded character facts; generated by scripts/import-jin-comparative.py.
import type { BranchLearning } from "./types";
export const jinComparativeLearning: BranchLearning[] = [
  {
    "branchId": "jin/shangdang",
    "words": [
      {
        "id": "zhi2024-changzhi-jin-t1-c1",
        "han": "站",
        "english": "Character 站",
        "ipa": "[tsɑŋ]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜅ · pitch not supplied",
        "note": "Zhi 2024, table 1: tsɑŋ꜅. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c2",
        "han": "盏",
        "english": "Character 盏",
        "ipa": "[tsɑŋ]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜂ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜂tsɑŋ. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c3",
        "han": "展",
        "english": "Character 展",
        "ipa": "[tsɑŋ]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜂ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜂tsɑŋ. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c4",
        "han": "战",
        "english": "Character 战",
        "ipa": "[tsɑŋ]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜅ · pitch not supplied",
        "note": "Zhi 2024, table 1: tsɑŋ꜅. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c5",
        "han": "抽",
        "english": "Character 抽",
        "ipa": "[tsʰəu]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀tsʰəu. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c6",
        "han": "愁",
        "english": "Character 愁",
        "ipa": "[tsʰəu]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜁ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜁tsʰəu. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c7",
        "han": "臭",
        "english": "Character 臭",
        "ipa": "[tsʰəu]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜄ · pitch not supplied",
        "note": "Zhi 2024, table 1: tsʰəu꜄. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c8",
        "han": "梳",
        "english": "Character 梳",
        "ipa": "[suə]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀suə. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-changzhi-jin-t1-c9",
        "han": "书",
        "english": "Character 书",
        "ipa": "[su]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "changzhi-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Luzhou, Changzhi · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀su. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Luzhou, Changzhi",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      }
    ],
    "soundNotes": [
      {
        "title": "梳 and 书: a vowel difference",
        "text": "In the Luzhou sample, 梳 has [suə] and 书 has [su]. Both carry the printed mark ꜀. These are segmental forms; the source does not provide their pitch values.",
        "localityIds": [
          "changzhi-jin"
        ],
        "source": {
          "title": "Zhi 2024 · table 1, p.4",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "title": "Same segments, different marks",
        "text": "站 and 战 have tsɑŋ꜅; 盏 and 展 have ꜂tsɑŋ. Their segment spelling is the same, while the printed tone marks differ. The sample is Luzhou speech from speakers born before 1952; the city map is an orientation anchor.",
        "localityIds": [
          "changzhi-jin"
        ],
        "source": {
          "title": "Zhi 2024 · table 1, p.4",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      }
    ],
    "culture": [
      {
        "title": "Shangdang Gate",
        "text": "At the north end of Fupo Street in Luzhou, Shangdang Gate marks the entrance to a former administrative compound. It remains a visible landmark of the old city.",
        "localityIds": [
          "changzhi-jin"
        ],
        "source": {
          "title": "Changzhi city government · 9 May 2025",
          "url": "https://www.changzhi.gov.cn/ztzl/cjwmwz/shfs/202505/t20250509_3044465.shtml"
        }
      },
      {
        "title": "Lu’an City God Temple",
        "text": "This Luzhou temple has three successive courtyards on a north–south axis. Its buildings retain features from the Yuan, Ming and Qing periods after repeated rebuilding.",
        "localityIds": [
          "changzhi-jin"
        ],
        "source": {
          "title": "Changzhi city government · 9 May 2025",
          "url": "https://www.changzhi.gov.cn/ztzl/cjwmwz/shfs/202505/t20250509_3044465.shtml"
        }
      }
    ],
    "resources": [
      {
        "title": "Luzhou character comparison",
        "description": "Table 1 gives nine character readings from the older-speaker sample. The Changzhi map is a city reference, not a surveyed speaker address.",
        "localityIds": [
          "changzhi-jin"
        ],
        "kind": "Study",
        "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
      },
      {
        "title": "Luzhou’s historic buildings",
        "description": "The city’s account locates Shangdang Gate and Lu’an City God Temple in Luzhou.",
        "localityIds": [
          "changzhi-jin"
        ],
        "kind": "Culture",
        "url": "https://www.changzhi.gov.cn/ztzl/cjwmwz/shfs/202505/t20250509_3044465.shtml"
      }
    ]
  },
  {
    "branchId": "jin/hanxin",
    "words": [
      {
        "id": "zhi2024-handan-jin-t1-c1",
        "han": "站",
        "english": "Character 站",
        "ipa": "[tʂa]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜄ · pitch not supplied",
        "note": "Zhi 2024, table 1: tʂa꜄. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c2",
        "han": "盏",
        "english": "Character 盏",
        "ipa": "[tʂa]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜂ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜂tʂa. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c3",
        "han": "展",
        "english": "Character 展",
        "ipa": "[tʂa]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜂ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜂tʂa. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c4",
        "han": "战",
        "english": "Character 战",
        "ipa": "[tʂa]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜄ · pitch not supplied",
        "note": "Zhi 2024, table 1: tʂa꜄. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c5",
        "han": "抽",
        "english": "Character 抽",
        "ipa": "[tʂʰou]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀tʂʰou. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c6",
        "han": "愁",
        "english": "Character 愁",
        "ipa": "[tʂʰou]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜁ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜁tʂʰou. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c7",
        "han": "臭",
        "english": "Character 臭",
        "ipa": "[tʂʰou]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜄ · pitch not supplied",
        "note": "Zhi 2024, table 1: tʂʰou꜄. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c8",
        "han": "梳",
        "english": "Character 梳",
        "ipa": "[ʂu]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀ʂu. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "id": "zhi2024-handan-jin-t1-c9",
        "han": "书",
        "english": "Character 书",
        "ipa": "[ʂu]",
        "toneNotation": "unspecified",
        "learningKind": "character-reading",
        "localityId": "handan-jin",
        "reading": "Character reading · segments only",
        "registerLabel": "Mazhuang, Handan · speakers born before 1952 · source mark ꜀ · pitch not supplied",
        "note": "Zhi 2024, table 1: ꜀ʂu. The displayed IPA retains the segments; the source tone mark is shown separately. The paper supplies no complete key for these marks. Publication year is not a fieldwork date.",
        "source": {
          "title": "Zhi 2024 · table 1, p.4 · Mazhuang, Handan",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      }
    ],
    "soundNotes": [
      {
        "title": "Three onset patterns",
        "text": "The Mazhuang sample gives 站 [tʂa], 抽 [tʂʰou] and 梳 [ʂu]: an unaspirated affricate, an aspirated affricate and a fricative. Pitch is not supplied in this comparison.",
        "localityIds": [
          "handan-jin"
        ],
        "source": {
          "title": "Zhi 2024 · table 1, p.4",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      },
      {
        "title": "A Mazhuang sample within Handan",
        "text": "抽, 愁 and 臭 share [tʂʰou] but carry different printed tone marks. These readings are from Mazhuang speakers born before 1952. The existing map point is in Congtai District for city orientation; it is not the Mazhuang fieldwork location.",
        "localityIds": [
          "handan-jin"
        ],
        "source": {
          "title": "Zhi 2024 · table 1, p.4",
          "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
        }
      }
    ],
    "culture": [
      {
        "title": "Handan Dao on foot",
        "text": "In the wider city, the Handan Dao pedestrian area links Congtai Park, Xuebu Bridge, cultural venues and a local-food street. This is city context for the Mazhuang reading sample.",
        "localityIds": [
          "handan-jin"
        ],
        "source": {
          "title": "Handan Commerce Bureau · 14 February 2026",
          "url": "https://hdsswj.hd.gov.cn/?a=view&p=3&r=5059"
        }
      },
      {
        "title": "Textile memories in the neighbourhood",
        "text": "Shuttle-shaped decorations in the Cotton Mill No. 3 residential community recall the city’s textile workers. A 2026 city report describes these details as part of neighbourhood renewal; this is wider Handan context.",
        "localityIds": [
          "handan-jin"
        ],
        "source": {
          "title": "Handan Housing and Urban–Rural Development Bureau · 12 January 2026",
          "url": "https://zjj.hd.gov.cn/html/handanyaowen/8342.html"
        }
      }
    ],
    "resources": [
      {
        "title": "Mazhuang character comparison",
        "description": "Table 1 identifies Mazhuang, Handan. The existing Congtai District map marker provides city orientation and is not the sample’s fieldwork location.",
        "localityIds": [
          "handan-jin"
        ],
        "kind": "Study",
        "url": "https://cjournal.hep.com.cn/1673-1646/CN/PDF/10.3969/j.issn.1673-1646.2023127#page=3"
      },
      {
        "title": "Walking Handan Dao",
        "description": "An official description of the city’s pedestrian district and nearby cultural venues.",
        "localityIds": [
          "handan-jin"
        ],
        "kind": "Culture",
        "url": "https://hdsswj.hd.gov.cn/?a=view&p=3&r=5059"
      },
      {
        "title": "Textile history in shared spaces",
        "description": "A city report documents shuttle-shaped decorations recalling textile work in the Cotton Mill No. 3 neighbourhood.",
        "localityIds": [
          "handan-jin"
        ],
        "kind": "Culture",
        "url": "https://zjj.hd.gov.cn/html/handanyaowen/8342.html"
      }
    ]
  }
];
