// Bounded factual examples; generated by scripts/import-tunxi-learning.py.
import type { BranchLearning } from "./types";
export const tunxiLearning: BranchLearning[] = [
  {
    "branchId": "hui/xiuyi",
    "words": [
      {
        "id": "lu2017-tunxi-first-weak",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "I",
        "ipa": "[a24]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Uncliticized weak pronoun",
        "registerLabel": "Tunxi · Lu 2017 · uncliticized weak pronoun · needs a following host",
        "note": "Needs a following host; not an isolated answer. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: a²⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: uncliticized singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-first-strong",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "I",
        "ipa": "[a24 le]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Strong pronoun",
        "registerLabel": "Tunxi · Lu 2017 · strong pronoun · tone on -le not supplied",
        "note": "Can stand alone or at clause end; the source supplies no tone on -le. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: a²⁴-le.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: strong singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-first-plural",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "we",
        "ipa": "[a24 ian44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Plural pronoun",
        "registerLabel": "Tunxi · Lu 2017 · plural pronoun",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: a²⁴-ian⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: plural",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-second-weak",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "you",
        "ipa": "[n̩44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Uncliticized weak pronoun",
        "registerLabel": "Tunxi · Lu 2017 · uncliticized weak pronoun · needs a following host",
        "note": "Needs a following host; not an isolated answer. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: n̩⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: uncliticized singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-second-strong",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "you",
        "ipa": "[n̩44 le]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Strong pronoun",
        "registerLabel": "Tunxi · Lu 2017 · strong pronoun · tone on -le not supplied",
        "note": "Can stand alone or at clause end; the source supplies no tone on -le. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: n̩⁴⁴-le.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: strong singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-second-plural",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "you (plural)",
        "ipa": "[n̩44 ian44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Plural pronoun",
        "registerLabel": "Tunxi · Lu 2017 · plural pronoun",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: n̩⁴⁴-ian⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: plural",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-third-weak",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "he/she",
        "ipa": "[kʰə44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Uncliticized weak pronoun",
        "registerLabel": "Tunxi · Lu 2017 · uncliticized weak pronoun · needs a following host",
        "note": "Needs a following host; not an isolated answer. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kʰə⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: uncliticized singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-third-strong",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "he/she",
        "ipa": "[kʰə44 le]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Strong pronoun",
        "registerLabel": "Tunxi · Lu 2017 · strong pronoun · tone on -le not supplied",
        "note": "Can stand alone or at clause end; the source supplies no tone on -le. Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kʰə⁴⁴-le.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: strong singular",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-third-plural",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "they",
        "ipa": "[kʰə44 ian44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Plural pronoun",
        "registerLabel": "Tunxi · Lu 2017 · plural pronoun",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kʰə⁴⁴-ian⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Diagram 2: plural",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-person",
        "han": "人",
        "learningKind": "word",
        "english": "person",
        "ipa": "[ian44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Free morpheme; also plural suffix",
        "registerLabel": "Tunxi · Lu 2017 · free morpheme; also plural suffix",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. Source form: ian⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.522, Footnote 2",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "id": "lu2017-tunxi-water",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "water",
        "ipa": "[ɕy31]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: ɕy³¹.",
        "source": {
          "title": "Lu Wen 2017 · p.525, Example 9",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=63"
        }
      },
      {
        "id": "lu2017-tunxi-tea",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "tea",
        "ipa": "[ʦɔ44]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: ʦɔ⁴⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.525, Example 9",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=63"
        }
      },
      {
        "id": "lu2017-tunxi-eat",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "eat",
        "ipa": "[ʨʰiʔ5]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: ʨʰiʔ⁵.",
        "source": {
          "title": "Lu Wen 2017 · p.527, Example 13a; also used with liquids in example 9",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=65"
        }
      },
      {
        "id": "lu2017-tunxi-rice",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "rice",
        "ipa": "[fuːə11]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. The printed colon marks vowel length; displayed as IPA ː. Source form: fu:ə¹¹.",
        "source": {
          "title": "Lu Wen 2017 · p.527, Example 13a",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=65"
        }
      },
      {
        "id": "lu2017-tunxi-talk",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "talk",
        "ipa": "[kau31]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kau³¹.",
        "source": {
          "title": "Lu Wen 2017 · p.523, Example 4",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=61"
        }
      },
      {
        "id": "lu2017-tunxi-go",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "go",
        "ipa": "[kʰə42]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kʰə⁴².",
        "source": {
          "title": "Lu Wen 2017 · p.525, Example 10",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=63"
        }
      },
      {
        "id": "lu2017-tunxi-home",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "home",
        "ipa": "[kɔ11]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: kɔ¹¹.",
        "source": {
          "title": "Lu Wen 2017 · p.529, Example 16A",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=67"
        }
      },
      {
        "id": "lu2017-tunxi-daughter",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "daughter",
        "ipa": "[len24]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: len²⁴.",
        "source": {
          "title": "Lu Wen 2017 · p.530, Example 21B",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=68"
        }
      },
      {
        "id": "lu2017-tunxi-negator",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "not (negation)",
        "ipa": "[pu11]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: pu¹¹.",
        "source": {
          "title": "Lu Wen 2017 · p.523, Example 4",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=61"
        }
      },
      {
        "id": "lu2017-tunxi-wine",
        "han": null,
        "writingStatus": "not-supplied",
        "learningKind": "word",
        "english": "wine",
        "ipa": "[ʦiu31]",
        "toneNotation": "pitch-contour",
        "localityId": "tunxi-hui",
        "reading": "Source sentence form",
        "registerLabel": "Tunxi · Lu 2017 · source sentence form",
        "note": "Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. The paper supplies IPA and a gloss, but no written form for this entry. Source form: ʦiu³¹.",
        "source": {
          "title": "Lu Wen 2017 · p.527, Example 14b",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=65"
        }
      }
    ],
    "soundNotes": [
      {
        "title": "A pronoun that can stand alone",
        "text": "Lu contrasts weak [a24], which needs a following host, with strong [a24-le], which can stand alone or occur at clause end. The same -le pattern appears with “you” and “he/she”. The paper leaves the tone of -le unmarked.",
        "localityIds": [
          "tunxi-hui"
        ],
        "source": {
          "title": "Lu 2017 · diagram 2 and section 2",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      },
      {
        "title": "Person and plural pronouns",
        "text": "The source gives 人 [ian44] “person” and plural [a24-ian44] “we”, [n̩44-ian44] “you” and [kʰə44-ian44] “they”. In [n̩44], the consonant itself forms the syllable. These are the paper’s Tunxi forms.",
        "localityIds": [
          "tunxi-hui"
        ],
        "source": {
          "title": "Lu 2017 · diagram 2 and footnote 2",
          "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=60"
        }
      }
    ],
    "culture": [
      {
        "title": "A street at three rivers",
        "text": "Tunxi Old Street developed beside the meeting of the Xin’an, Heng and Shuaishui rivers. Its main street, three cross streets and eighteen lanes preserve the layout of a historic commercial neighbourhood.",
        "localityIds": [
          "tunxi-hui"
        ],
        "source": {
          "title": "Huangshan government · Tunxi Old Street",
          "url": "https://www.huangshan.gov.cn/zwgk/public/6615714/11221464.html"
        }
      },
      {
        "title": "Inkstones, carving and everyday objects",
        "text": "Tunxi Museum on Old Street displays Xin’an painting and calligraphy, She inkstones, Hui carving and furniture. Its community-history displays trace the work and daily lives of the old street’s residents.",
        "localityIds": [
          "tunxi-hui"
        ],
        "source": {
          "title": "Tunxi Old Street administration · Tunxi Museum",
          "url": "https://www.huangshan.gov.cn/zwgk/grassroots/6616081/10336250.html"
        }
      }
    ],
    "resources": [
      {
        "title": "Tunxi pronouns in context",
        "description": "Lu’s 2017 study explains where weak and strong pronouns can occur, with interlinear sentence examples.",
        "localityIds": [
          "tunxi-hui"
        ],
        "kind": "Study",
        "url": "https://bpb-us-w2.wpmucdn.com/u.osu.edu/dist/2/123895/files/2024/04/NACCL-29-Vol2_Part-9-a-8d0dc119fb9d1887.pdf#page=57"
      },
      {
        "title": "Tunxi community museum",
        "description": "The local administration describes the museum’s collections and the old street’s community-history displays.",
        "localityIds": [
          "tunxi-hui"
        ],
        "kind": "Culture",
        "url": "https://www.huangshan.gov.cn/zwgk/grassroots/6616081/10336250.html"
      }
    ]
  }
];
