// Licensed factual examples; generated by scripts/import-weizilu-learning.py.
import type { BranchLearning } from "./types";
export const weiziluLearning: BranchLearning[] = [
  {
    "branchId": "pinghua/southern-pinghua",
    "words": [
      {
        "id": "desousa2024-weizilu-chick-er",
        "han": "雞兒",
        "english": "chick",
        "ipa": "[kɐi53 ɲi21]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Citation-tone suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · citation-tone suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: kɐi⁵³ -ɲi²¹. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-kid",
        "han": "羊兒",
        "english": "kid (young goat)",
        "ipa": "[jɐŋ21 ɲi21]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Citation-tone suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · citation-tone suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: jɐŋ²¹ -ɲi²¹. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-car-low",
        "han": "車兒",
        "english": "little car",
        "ipa": "[tʃʰɛ53 ɲi21]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Citation-tone suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · citation-tone suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tʃʰɛ⁵³ -ɲi²¹. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-knife-er",
        "han": "刀兒",
        "english": "little knife",
        "ipa": "[tau53 ɲi21]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Citation-tone suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · citation-tone suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tau⁵³ -ɲi²¹. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-car-high",
        "han": "車兒",
        "english": "little car",
        "ipa": "[tʃʰɛ53 ɲi53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tʃʰɛ⁵³ -ɲi²¹⁻⁵³. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-house",
        "han": "屋兒",
        "english": "little house",
        "ipa": "[ʊk3 ɲi53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: ʊk³ -ɲi²¹⁻⁵³. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-wok",
        "han": "鐺兒",
        "english": "little wok",
        "ipa": "[tʃʰɛŋ53 ɲi53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tʃʰɛŋ⁵³ -ɲi⁵³. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.17, Section 3.2, Weizilu paragraph; gloss continues on p.18 · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "id": "desousa2024-weizilu-puppy-high",
        "han": "狗兒",
        "english": "puppy",
        "ipa": "[kɐu33 ɲi53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: kɐu³³ -ɲi²¹⁻⁵³. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-puppy-low",
        "han": "狗兒",
        "english": "puppy",
        "ipa": "[kɐu33 ɲi21]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Citation-tone suffix; more common in the source",
        "registerLabel": "Weizilu · de Sousa 2024 · citation-tone suffix; more common in the source",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: kɐu³³ -ɲi²¹. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-chick-zai",
        "han": "雞仔",
        "english": "chick",
        "ipa": "[kɐi53 tʃai33]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Newer diminutive suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · newer diminutive suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: kɐi⁵³ -tʃai³³. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-piglet",
        "han": "豬仔",
        "english": "piglet",
        "ipa": "[tʃəi53 tʃai33]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Newer diminutive suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · newer diminutive suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tʃәi⁵³ -tʃai³³. The source’s schwa glyph ә is displayed as IPA ə. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-knife-zai",
        "han": "刀仔",
        "english": "little knife",
        "ipa": "[tau53 tʃai33]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Newer diminutive suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · newer diminutive suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: tau⁵³ -tʃai³³. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-bowl",
        "han": "碗仔",
        "english": "little bowl",
        "ipa": "[un33 tʃai33]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "Newer diminutive suffix",
        "registerLabel": "Weizilu · de Sousa 2024 · newer diminutive suffix",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: un³³ -tʃai³³. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-yuan",
        "han": "文",
        "english": "yuan",
        "ipa": "[mɐn53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling tone replacement",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling tone replacement",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: mɐn²¹⁻⁵³. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-mother",
        "han": "老娘",
        "english": "mother",
        "ipa": "[lau13 nɛŋ53]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-falling tone replacement",
        "registerLabel": "Weizilu · de Sousa 2024 · high-falling tone replacement",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: lau¹³ nɛŋ²¹⁻⁵³. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-aunt",
        "han": "姨娘",
        "english": "mother’s younger sister",
        "ipa": "[həi21 nɛŋ55]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-level tone replacement",
        "registerLabel": "Weizilu · de Sousa 2024 · high-level tone replacement",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: hәi²¹ nɛŋ²¹⁻⁵⁵. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. The source’s schwa glyph ә is displayed as IPA ə. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-grandmother",
        "han": "奶奶",
        "english": "paternal grandmother",
        "ipa": "[nai55 nai55]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-level tone replacement",
        "registerLabel": "Weizilu · de Sousa 2024 · high-level tone replacement",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: nai¹³⁻⁵⁵ nai¹³⁻⁵⁵. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      },
      {
        "id": "desousa2024-weizilu-grandfather",
        "han": "爺爺",
        "english": "paternal grandfather",
        "ipa": "[jɛ21 jɛ35]",
        "toneNotation": "pitch-contour",
        "learningKind": "word",
        "localityId": "weizilu-pinghua",
        "reading": "High-rising tone replacement; Cantonese loan",
        "registerLabel": "Weizilu · de Sousa 2024 · high-rising tone replacement; cantonese loan",
        "note": "Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: jɛ²¹ jɛ²¹⁻³⁵. The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. Adapted from de Sousa 2024, CC BY 4.0.",
        "source": {
          "title": "de Sousa 2024 · p.18, Section 3.2, Weizilu paragraph · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      }
    ],
    "soundNotes": [
      {
        "title": "Two forms of “little car”",
        "text": "The Weizilu sample gives 車兒 [tʃʰɛ53 ɲi21] and [tʃʰɛ53 ɲi53]. The second form changes the suffix tone. The source writes its underlying and pronounced tones as 21–53; only 53 is spoken in that form.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "source": {
          "title": "de Sousa 2024 · pp.2,17 · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
        }
      },
      {
        "title": "More than one diminutive suffix",
        "text": "The source gives 雞兒 [kɐi53 ɲi21] and 雞仔 [kɐi53 tʃai33] for a chick. It describes the second suffix as newer and influenced by Nanning Cantonese. Suffix choice varies by noun; these examples do not establish a rule for every word.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "source": {
          "title": "de Sousa 2024 · pp.17–18 · CC BY 4.0",
          "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=19"
        }
      }
    ],
    "culture": [
      {
        "title": "New Year couplets",
        "text": "At Weizilu’s January 2025 New Year gathering, visiting art teachers wrote festive couplets for residents and joined the community’s games. The university’s account records the exchange of handwritten wishes as part of the celebration.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "source": {
          "title": "Nanning Vocational Technology University · 24 January 2025",
          "url": "https://ysxy.nnvtu.edu.cn/info/1231/12412.htm"
        }
      },
      {
        "title": "Keeping neighbourhood memories",
        "text": "In June 2026, Weizilu community staff and a university design team discussed small changes to public spaces, building colours and materials. Their plans included retaining community memories while adapting shared spaces to residents’ needs.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "source": {
          "title": "Nanning Vocational Technology University · 22 June 2026",
          "url": "https://jzxy.nnvtu.edu.cn/info/1269/8134.htm"
        }
      }
    ],
    "resources": [
      {
        "title": "Weizilu words and tone replacement",
        "description": "De Sousa’s field examples appear on pp.17–18; Appendix B identifies Weizilu as the author’s own fieldwork. CC BY 4.0.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "kind": "Study",
        "url": "https://hilario.bambooradical.com/downloadables/languages-09-00311-with-cover.pdf#page=18"
      },
      {
        "title": "New Year in Weizilu",
        "description": "A participating university’s account of couplet writing and the community’s January 2025 gathering.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "kind": "Culture",
        "url": "https://ysxy.nnvtu.edu.cn/info/1231/12412.htm"
      },
      {
        "title": "Community spaces and local memory",
        "description": "A university field visit identifies Weizilu community in Xixiangtang and records discussion of neighbourhood renewal.",
        "localityIds": [
          "weizilu-pinghua"
        ],
        "kind": "Culture",
        "url": "https://jzxy.nnvtu.edu.cn/info/1269/8134.htm"
      }
    ]
  }
];
