import { createServer } from "vite";
import { writeFile } from "node:fs/promises";
const server = await createServer({
  server: { middlewareMode: true },
  appType: "custom",
});
try {
  const { contentDepth } = await server.ssrLoadModule(
    "/src/data/content-depth.ts",
  );
  const { atlasBranches, atlasClusters, atlasLocalities, atlasLocalityPath } = await server.ssrLoadModule("/src/data/atlas/index.ts");
  const { languages } = await server.ssrLoadModule("/src/data/languages.ts");
  const atlasLines = ["# Four-level atlas inventory", "", "Generated by `npm run audit:content`. Locality references are sourced catalogue entries; developed learning collections are counted separately in CONTENT-DEPTH.md.", "", `**${atlasBranches.length} branches · ${atlasClusters.length} clusters or geographic collections · ${atlasLocalities.length} locality references**`, "", "| Group | Branches | Clusters / collections | Locality references |", "| --- | ---: | ---: | ---: |", ...languages.map(language => language.id).map(group => `| ${group} | ${atlasBranches.filter(b=>b.groupId===group).length} | ${atlasClusters.filter(c=>c.groupId===group).length} | ${atlasLocalities.filter(p=>p.groupId===group).length} |`), "", "## Localities", "", "| Locality | Canonical path | Source locator |", "| --- | --- | --- |", ...atlasLocalities.map(p=>`| ${p.name} · ${p.nativeName} | ${atlasLocalityPath(p)} | [${p.source.title}](${p.source.url}) — ${p.source.locator.replaceAll('|', '/')} |`), ""];
  await writeFile("docs/ATLAS-INVENTORY.md", atlasLines.join("\n"));
  console.log(`Atlas: ${atlasLocalities.length} references across ${atlasBranches.length} branches and ${atlasClusters.length} clusters/collections.`);
  const branches = contentDepth();
  const places = branches.flatMap((branch) => branch.places);
  const taughtPlaces = places.filter(place => place.ipaWords > 0);
  const photographedPlaces = places.filter(place => place.photos > 0);
  const baseline = places.find(place => place.localityId === "xiamen");
  const parity = places.filter(place => place.ipaWords >= baseline.ipaWords && place.photos >= baseline.photos && place.soundNotes >= 2 && place.cultureTopics >= 2 && place.learningSources >= 2);
  const { getLocalGallery } = await server.ssrLoadModule("/src/data/galleries/index.ts");
  const uniquePhotos = new Set(places.flatMap(place => getLocalGallery(place.localityId).map(photo => photo.src))).size;
  const total = (key) => places.reduce((sum, place) => sum + place[key], 0);
  const lines = [
    "# Content depth audit",
    "",
    "Generated from the published data models with `npm run audit:content`. Counts describe entries, not a quality score or a claim of complete language coverage. Character readings are distinguished from phrase lessons in their source notes. Photograph counts do not stand in for vocabulary depth.",
    "",
    `Inventory: **${branches.length} branches · ${places.length} locality references**. Actual learning coverage: **${taughtPlaces.length} localities with IPA**, **${photographedPlaces.length} with photos**, **${total("ipaWords")} IPA entries**, **${total("sourceSpellingWords")} additional source-spelling entries**, **${total("photos")} gallery placements of ${uniquePhotos} distinct image assets**, **${total("hostedRecordings")} inline local recordings**, **${total("linkedRecordings")} original-publisher listening links**.`,
    "",
    `Amoy-count benchmark: ${baseline.ipaWords} source readings and ${baseline.photos} photographs, plus at least 2 sound notes, 2 cultural topics and 2 useful source links. **${parity.length} of ${places.length} localities meet these count thresholds.** Counts alone do not establish teaching quality or complete coverage; related-place links never count as local lessons.`,
    "",
    `Separately typed character readings: **${total("characterReadings")}** (included in IPA entries, excluded from meaning quizzes). Source citation-tone inventories: **${total("citationToneInventories")}** with **${total("citationToneCategories")}** category/contour pairs; these are not words or recordings.`,
    "",
    `Of the IPA entries, ${total("segmentalEntries")} retain source transcriptions with tones omitted. Their cards explicitly say that tones are not given.`,
    "",
    "## Branch inventory",
    "",
    "| Branch | Places | IPA entries | All word entries | Photos | Sound notes | Culture topics | Local source links |",
    "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ...branches.map(
      (branch) =>
        `| ${branch.branchId} | ${branch.localities} | ${branch.ipaWords} | ${branch.words} | ${branch.photos} | ${branch.soundNotes} | ${branch.cultureTopics} | ${branch.learningSources} |`,
    ),
    "",
    "Gallery placements may share city photographs across language references, as in Singapore. This is not a count of additional photographs or evidence of the language spoken by pictured people. Original-publisher listening links are separate from inline recordings, general IPA demonstrations and character readings.",
    "",
    "Source links are counted per locality; a shared dictionary may appear under multiple appropriate locality references. A multi-locality learning note is likewise counted for each locality it explicitly supports.",
    "",
    "## Locality inventory",
    "",
    "| Locality | IPA entries | Source-spelling entries | IPA with tones omitted | Photos | Sound notes | Culture topics | Source links | Chapters |",
    "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ...places.map(
      (place) =>
        `| ${place.localityId} | ${place.ipaWords} | ${place.sourceSpellingWords} | ${place.segmentalEntries} | ${place.photos} | ${place.soundNotes} | ${place.cultureTopics} | ${place.learningSources} | ${place.sections.join(", ")} |`,
    ),
    "",
    "## Research priorities",
    "",
    "A working starter target is 20 attested readings, 3 specific sound notes, 2 cultural topics and 2 useful source links per locality. This is a research queue, not permission to add unverified forms or pad the prose. Shared locality pages now include topic browsing, bookmarks, saved-word practice and a visual pitch explorer wherever the evidence supports them; Amoy retains its dedicated lessons. Lower counts remain visible here so photo-rich pages cannot be mistaken for complete language courses.",
    "",
    ...places
      .filter((place) => place.ipaWords < 20)
      .map(
        (place) =>
          `- **${place.localityId}:** ${place.ipaWords} attested IPA entries${place.sourceSpellingWords ? ` and ${place.sourceSpellingWords} separately labelled source-spelling entries` : ""}. Expand from locality-specific dictionaries or speaker-documented studies; do not copy neighbouring accents.`,
      ),
    "",
    "## Evidence rules",
    "",
    "- Every word retains its locality, reading convention and source. Source tone categories are not pitch contours.",
    "- Regional spelling-only forms remain under their original notation; they do not generate invented IPA or HanLingo pitch numbers.",
    "- The shared tree remains the navigation structure. Group and branch overviews surface sampled learning material; complete available word collections remain under locality Words pages.",
    "- Galleries retain 9–11 distinct licensed photos per developed learning locality. Photo subjects never establish the language or identity of the people pictured.",
    "",
  ];
  await writeFile("docs/CONTENT-DEPTH.md", lines.join("\n"));
  console.log(
    `Audited ${branches.length} branches and ${places.length} localities: ${total("ipaWords")} IPA entries, ${total("sourceSpellingWords")} source-spelling entries, ${total("photos")} photos.`,
  );
  console.log(`IPA localities: ${taughtPlaces.length}; photo localities: ${photographedPlaces.length}; Amoy-count benchmark: ${parity.length}/${places.length}.`);
  console.log("Written docs/CONTENT-DEPTH.md");
} finally {
  await server.close();
}
