#!/usr/bin/env python3
"""Reproduce licensed de Sousa 2024 lexical examples with explicit suprafix realization."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
ledger=json.loads((ROOT/'docs/weizilu-learning-provenance.json').read_text())
url=ledger['source']['url']
def realized(raw):
    text=raw.translate(str.maketrans('⁰¹²³⁴⁵⁶⁷⁸⁹⁻','0123456789~')).replace('ә','ə')
    text=re.sub(r'[1-5]+~([1-5]+)',r'\1',text)
    return text.replace(' -',' ')
words=[]
for r in ledger['rows']:
    sup='⁻' in r['sourceIpa']
    words.append({'id':r['id'],'han':r['han'],'english':r['gloss'],'ipa':'['+realized(r['sourceIpa'])+']','toneNotation':'pitch-contour','learningKind':'word','localityId':'weizilu-pinghua','reading':r['register'],'registerLabel':'Weizilu · de Sousa 2024 · '+r['register'].lower(),
      'note':'Author’s Weizilu fieldwork, published 2024; speaker biography and collection date are not supplied. Source form: '+r['sourceIpa']+'. '+('The source’s superscript hyphen separates an underlying tone from its pronounced replacement. Displayed IPA uses only the pronounced tone, following §1.1. ' if sup else '')+('The source’s schwa glyph ә is displayed as IPA ə. ' if 'ә' in r['sourceIpa'] else '')+'Adapted from de Sousa 2024, CC BY 4.0.',
      'source':{'title':f"de Sousa 2024 · p.{r['printedPage']}, {r['locator']} · CC BY 4.0",'url':url+f"#page={r['pdfPageOneBased']}"}})
def item(title,text,sourceTitle,sourceUrl):
 return {'title':title,'text':text,'localityIds':['weizilu-pinghua'],'source':{'title':sourceTitle,'url':sourceUrl}}
renew='https://jzxy.nnvtu.edu.cn/info/1269/8134.htm'
newyear='https://ysxy.nnvtu.edu.cn/info/1231/12412.htm'
pack={'branchId':'pinghua/southern-pinghua','words':words,
'soundNotes':[
item('Two forms of “little car”','The Weizilu sample gives 車兒 [tʃʰɛ53 ɲi21] and [tʃʰɛ53 ɲi53]. The second form changes the suffix tone. The source writes its underlying and pronounced tones as 21–53; only 53 is spoken in that form.','de Sousa 2024 · pp.2,17 · CC BY 4.0',url+'#page=18'),
item('More than one diminutive suffix','The source gives 雞兒 [kɐi53 ɲi21] and 雞仔 [kɐi53 tʃai33] for a chick. It describes the second suffix as newer and influenced by Nanning Cantonese. Suffix choice varies by noun; these examples do not establish a rule for every word.','de Sousa 2024 · pp.17–18 · CC BY 4.0',url+'#page=19')],
'culture':[
item('New Year couplets','At Weizilu’s January 2025 New Year gathering, visiting art teachers wrote festive couplets for residents and joined the community’s games. The university’s account records the exchange of handwritten wishes as part of the celebration.','Nanning Vocational Technology University · 24 January 2025',newyear),
item('Keeping neighbourhood memories','In June 2026, Weizilu community staff and a university design team discussed small changes to public spaces, building colours and materials. Their plans included retaining community memories while adapting shared spaces to residents’ needs.','Nanning Vocational Technology University · 22 June 2026',renew)],
'resources':[
{'title':'Weizilu words and tone replacement','description':'De Sousa’s field examples appear on pp.17–18; Appendix B identifies Weizilu as the author’s own fieldwork. CC BY 4.0.','localityIds':['weizilu-pinghua'],'kind':'Study','url':url+'#page=18'},
{'title':'New Year in Weizilu','description':'A participating university’s account of couplet writing and the community’s January 2025 gathering.','localityIds':['weizilu-pinghua'],'kind':'Culture','url':newyear},
{'title':'Community spaces and local memory','description':'A university field visit identifies Weizilu community in Xixiangtang and records discussion of neighbourhood renewal.','localityIds':['weizilu-pinghua'],'kind':'Culture','url':renew}]}
(ROOT/'src/data/learning/weizilu.ts').write_text('// Licensed factual examples; generated by scripts/import-weizilu-learning.py.\nimport type { BranchLearning } from "./types";\nexport const weiziluLearning: BranchLearning[] = '+json.dumps([pack],ensure_ascii=False,indent=2)+';\n')
print('Weizilu:',len(words),'forms')
