#!/usr/bin/env python3
"""Build a bounded factual Hui sample from the manually reviewed versioned ledger.

This is deliberately not an OCR parser: the scanned IPA tables need visual review.
Source table images are research evidence only and are never copied to public/.
"""
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ledger = json.loads((ROOT / 'docs/hui-wuyuan-provenance.json').read_text())
source_pdf = ROOT / '.evidence/hui-jin-next/hu2016-hui.pdf'
if source_pdf.exists():
    assert hashlib.sha256(source_pdf.read_bytes()).hexdigest() == ledger['source']['sha256']
assert len(ledger['rows']) == 19
assert len({r['id'] for r in ledger['rows']}) == 19
words = []
for r in ledger['rows']:
    assert r['table'] in [6, 7, 12] and r['pdfPage'] == r['page'] - 65
    assert not any(char in r['han'] for char in '囗□*')
    note = 'Hu’s 2015 village survey, published 2016. One male lifelong resident; the study normally selected speakers aged 60 or above. Source pitch digits retain the printed values. '
    if r['mergedHeadwords']:
        note += f"The source’s merged cell explicitly covers {r['mergedHeadwords']}. "
    if r['note']:
        note += r['note'] + ' '
    note += 'Character identification only; no everyday lexical meaning or present-day uniform village accent is inferred.'
    words.append(dict(id=r['id'], han=r['han'], english=f"Character {r['han']}",
        ipa=f"[{r['sourceReading']}]", toneNotation='pitch-contour', localityId=ledger['localityId'],
        learningKind='character-reading', reading='Survey character reading',
        registerLabel='Youshan village · 2015 survey · one older speaker · character reading',
        note=note, source={'title':f"Hu Guiyue 2016 · p.{r['page']}, table {r['table']}, 游山 row, column {r['column']}",
        'url':ledger['source']['url'] + f"#page={r['pdfPage']}"}))
pack = dict(branchId=ledger['branchId'], words=words, soundNotes=ledger['soundNotes'],
            culture=ledger['culture'], resources=ledger['resources'])
(ROOT/'src/data/learning/hui-wuyuan.ts').write_text(
    '// Bounded character-reading selection; generated by scripts/import-hui-wuyuan.py.\n'
    'import type { BranchLearning } from "./types";\n'
    'export const huiWuyuanLearning: BranchLearning[] = ' + json.dumps([pack],ensure_ascii=False,indent=2) + ';\n')
(ROOT/'src/data/atlas/hui-wuyuan-localities.ts').write_text(
    '// A village reference, not a township-wide accent.\n'
    'import type { AtlasLocality } from "./types";\n'
    'export const atlasHuiWuyuanLocalities: AtlasLocality[] = ' + json.dumps([ledger['locality']],ensure_ascii=False,indent=2) + ';\n')
print(f"Generated {len(words)} Youshan character readings and one village reference.")
