#!/usr/bin/env python3
"""Reproduce the bounded Lu 2017 Tunxi selection from its reviewed provenance ledger."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ledger = json.loads((ROOT / 'docs/tunxi-learning-provenance.json').read_text())
def source(title, page=None):
    return {'title': title, 'url': ledger['source']['download'] + (f'#page={page}' if page else '')}
def normalize(ipa):
    return ipa.translate(str.maketrans('⁰¹²³⁴⁵⁶⁷⁸⁹', '0123456789')).replace(':', 'ː').replace('-', ' ')
words = []
for row in ledger['rows']:
    strong = row['register'] == 'Strong pronoun'
    label = 'Tunxi · Lu 2017 · ' + row['register'].lower()
    if strong: label += ' · tone on -le not supplied'
    elif row['register'] == 'Uncliticized weak pronoun': label += ' · needs a following host'
    words.append({
        'id': 'lu2017-tunxi-' + row['id'], 'han': row['sourceHan'],
        **({'writingStatus': 'not-supplied'} if row['sourceHan'] is None else {}),
        'learningKind': 'word', 'english': 'not (negation)' if row['gloss'] == 'NEG' else row['gloss'],
        'ipa': '[' + normalize(row['sourceIpa']) + ']', 'toneNotation': 'pitch-contour',
        'localityId': 'tunxi-hui', 'reading': row['register'], 'registerLabel': label,
        'note': (row['qualification'] + ' ' if row['qualification'] else '') + 'Lu’s 2017 paper identifies Tunxi, without a neighbourhood, speaker biography or collection date. ' + ('The paper supplies IPA and a gloss, but no written form for this entry. ' if row['sourceHan'] is None else '') + ('The printed colon marks vowel length; displayed as IPA ː. ' if ':' in row['sourceIpa'] else '') + 'Source form: ' + row['sourceIpa'] + '.',
        'source': source(f"Lu Wen 2017 · p.{row['printedPage']}, {row['locator']}", row['pdfPageOneBased'])})
def item(title,text,url,titleSource):
    return {'title':title,'text':text,'localityIds':['tunxi-hui'],'source':{'title':titleSource,'url':url}}
oldstreet = 'https://www.huangshan.gov.cn/zwgk/public/6615714/11221464.html'
museum = 'https://www.huangshan.gov.cn/zwgk/grassroots/6616081/10336250.html'
pack = {'branchId':'hui/xiuyi','words':words,
'soundNotes':[
item('A pronoun that can stand alone', 'Lu contrasts weak [a24], which needs a following host, with strong [a24-le], which can stand alone or occur at clause end. The same -le pattern appears with “you” and “he/she”. The paper leaves the tone of -le unmarked.', source('',60)['url'], 'Lu 2017 · diagram 2 and section 2'),
item('Person and plural pronouns', 'The source gives 人 [ian44] “person” and plural [a24-ian44] “we”, [n̩44-ian44] “you” and [kʰə44-ian44] “they”. In [n̩44], the consonant itself forms the syllable. These are the paper’s Tunxi forms.',source('',60)['url'],'Lu 2017 · diagram 2 and footnote 2')],
'culture':[
item('A street at three rivers', 'Tunxi Old Street developed beside the meeting of the Xin’an, Heng and Shuaishui rivers. Its main street, three cross streets and eighteen lanes preserve the layout of a historic commercial neighbourhood.',oldstreet,'Huangshan government · Tunxi Old Street'),
item('Inkstones, carving and everyday objects', 'Tunxi Museum on Old Street displays Xin’an painting and calligraphy, She inkstones, Hui carving and furniture. Its community-history displays trace the work and daily lives of the old street’s residents.',museum,'Tunxi Old Street administration · Tunxi Museum')],
'resources':[
{'title':'Tunxi pronouns in context','description':'Lu’s 2017 study explains where weak and strong pronouns can occur, with interlinear sentence examples.','localityIds':['tunxi-hui'],'kind':'Study','url':source('',57)['url']},
{'title':'Tunxi community museum','description':'The local administration describes the museum’s collections and the old street’s community-history displays.','localityIds':['tunxi-hui'],'kind':'Culture','url':museum}]}
(ROOT/'src/data/learning/tunxi.ts').write_text('// Bounded factual examples; generated by scripts/import-tunxi-learning.py.\nimport type { BranchLearning } from "./types";\nexport const tunxiLearning: BranchLearning[] = '+json.dumps([pack],ensure_ascii=False,indent=2)+';\n')
print('Tunxi:',len(words),'forms;',sum(w['han'] is None for w in words),'without supplied Han')
